### ISSUE TITLE
XCFramework delivery planned?

### ISSUE THREAD

**Issue by mlostekk** [taplytics/taplytics-ios-sdk#101]
Are there plans to provide taplytics as universal xcframeworks? (i am looking at you M1 macs using simulators)

**Comment by leslie-lau** [comment]
Hi @mlostekk I've spoken to our product team and we've added this item to our long-term road map.

**Comment by mlostekk** [comment]
Wow, considering this as "long-term" feature is a showstopper for a lot of customers that are using the latest xcode for all platforms. Unfortunately we also have to move on to a different AB testing tool in this case.

**Comment by leslie-lau** [comment]
Hi @mlostekk, thanks for the comment! Let me reconnect with my team in early January with your feedback and see if we can get that moved up in priority.

**Comment by mlostekk** [comment]
thanks, but we have already chosen a different tool.

**Comment by dcilia** [comment]
@leslie-lau Hello, can we reopen this and have it prioritized?  We have moved to SPM for all our 3rd party packages.  I suggest scoping out adding SPM support + xcframework (for Apple Silicon M1 support as well)
