### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by malikalayli** [taplytics/taplytics-ios-sdk#11]
Hi,

On the first startup, Taplytics works well but on the second startup, it crashes.

I have set -ObjC in "other linker flags".

Is there an option to be set?

Best Regards,

Malik Alayli

**Comment by andrewnorris** [comment]
Hi Malik,

It was great speaking with your team earlier today. As mentioned in my email, please let us know if you have any log files of the build crash and we'd be happy to get it fully set up for you.

Best,

Andrew
