### ISSUE TITLE
infinite loop crash

### ISSUE THREAD

**Issue by johnryan** [taplytics/taplytics-ios-sdk#12]
getting an infinite loop crash with the TLViewController category:

0x004baccb -[UIViewController(TLViewController) tlsw_viewDidLoad] + 615446
0x2804846d -[UIViewController loadViewIfRequired] + 600
0x280481dd -[UIViewController view] + 24
0x004baccb -[UIViewController(TLViewController) tlsw_viewDidLoad] + 615446
0x2804846d -[UIViewController loadViewIfRequired] + 600
0x280481dd -[UIViewController view] + 24
0x004baccb -[UIViewController(TLViewController) tlsw_viewDidLoad]

**Comment by jonathannorris** [comment]
@johnryan 
What version of the SDK are you running? we just fixed a similar issue in a recent update.

Also if you could send us a full stack trace of the issue and possible a screenshot of where the crash is happening that would be awesome: support@taplytics.com

**Comment by johnryan** [comment]
using version: 2.0.10

Unfortunately don't have a screenshot as Its happening in a production app and I can't reproduce. The stack trace is pretty uninteresting my crash reporter just shows what i posted above for as far back as it goes on the main thread.

**Comment by jonathannorris** [comment]
Ok I believe we have this issue solved in 2.1.26, please update the SDK to that version and feel free to contact us if you see any more issues.

**Comment by peckda** [comment]
@jonathannorris 

When integrating the SDK today (2.1.26), I also had it freeze in a loop:

SendDelegateMessage(NSInvocation *): delegate (webView:identifierForInitialRequest:fromDataSource:) failed to return after waiting 10 seconds

Unfortunately (fortunately?) I haven't been able to reproduce.  Not sure if it is related, but I'll open an issue if it occurs again.

**Comment by jonathannorris** [comment]
@peckda 

That looks like an issue I have been debugging with the socket.io library we are using, we only use socket.io in development builds (to connect the device with the website) so its not a critical production issue. Hopefully I'll have a fix out today or tomorrow for it, if you see the issue again feel free to send over the stack trace: support@taplytics.com
