### ISSUE TITLE
Crash on iOS7

### ISSUE THREAD

**Issue by benagarr** [taplytics/taplytics-ios-sdk#13]
Maybe it's calling the wrong selector on ios7....

Last Exception Backtrace:
0   CoreFoundation                	0x30806f7e __exceptionPreprocess + 126
1   libobjc.A.dylib               	0x3b4b4cca objc_exception_throw + 34
2   CoreFoundation                	0x3080a912 -[NSObject(NSObject) doesNotRecognizeSelector:] + 198
3   CoreFoundation                	0x308091fe ___forwarding___ + 702
4   CoreFoundation                	0x30758764 _CF_forwarding_prep_0 + 20
5   Roll                          	0x007260f8 -[TLPushManager checkHasPushToken] + 336
6   Roll                          	0x0071148a __41-[TLManager startTaplyticsAPIKey:server:]_block_invoke227 + 270
7   libdispatch.dylib             	0x3b99c82e _dispatch_call_block_and_release + 6
8   libdispatch.dylib             	0x3b99c81a _dispatch_client_callout + 18
9   libdispatch.dylib             	0x3b9a349a _dispatch_main_queue_callback_4CF$VARIANT$mp + 274
10  CoreFoundation                	0x307d189c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 4
11  CoreFoundation                	0x307d0170 __CFRunLoopRun + 1296
12  CoreFoundation                	0x3073aeba CFRunLoopRunSpecific + 518
13  CoreFoundation                	0x3073ac9e CFRunLoopRunInMode + 102
14  GraphicsServices              	0x3566e65e GSEventRunModal + 134
15  UIKit                         	0x33087148 UIApplicationMain + 1132
16  Roll                          	0x003d759c main (main.swift:10)
17  libdyld.dylib                 	0x3b9c1ab2 tlv_initializer + 2

**Comment by jonathannorris** [comment]
Thanks for letting us know, I actually ran into this issue while testing today. Added a test for it to our build system. 

SDK 2.1.56 fixes it!
