### ISSUE TITLE
Crash on Startup in iOS 7

### ISSUE THREAD

**Issue by peckda** [taplytics/taplytics-ios-sdk#15]
Got an infinite loop crash on startup.  Using .72

I've attached an image.  For now, I'm disabling Taplytics in iOS 7.
![screen shot 2015-04-18 at 9 48 47 pm](https://cloud.githubusercontent.com/assets/335305/7218199/0714504e-e615-11e4-96a0-051185b03655.png)

**Comment by jonathannorris** [comment]
@peckda any chance you could send over the stack trace and a screen shot of the view that it's happening on to: support@taplytics.com? We should be able to solve this quickly for you.

**Comment by john-langley** [comment]
+1 I have the same behavior on 7.1

**Comment by jonathannorris** [comment]
@john-langley what version of the SDK are you currently on? If you are seeing this issue in production contact us and we are able to remotely fix the issue for you: support@taplytics.com

**Comment by john-langley** [comment]
@jonathannorris I was on 2.1.70, but still see the issue after upgrading to 2.1.72 ... this isn't in production yet, but we're planning to submit today.

**Comment by jonathannorris** [comment]
Hey @john-langley, we have a fix for the issue that you and @peckda are seeing here. Just running through some final QA and we will be pushing it live this afternoon. I'll close this issue when 2.1.74 is live.

**Comment by jonathannorris** [comment]
version 2.1.74 has been pushed with the fix.

**Comment by john-langley** [comment]
@jonathannorris All good - thanks, man.
