### ISSUE TITLE
TLView BAD_ACCESS exception when setting frame on background thread

### ISSUE THREAD

**Issue by john-langley** [taplytics/taplytics-ios-sdk#16]
We're seeing exceptions in production that seem to be caused by the Taplytics SDK.  We have active experiments, however we only use variations for feature flipping (we're not A/B testing view variants via Taplytics).  

Stack trace here (exception caught at line 7):

EXC_BAD_ACCESS KERN_INVALID_ADDRESS

Thread : Crashed: WebThread
0  UIKit                          0x25d6b4f2 -[_UIViewAdditiveAnimationAction runActionForKey:object:arguments:] + 569
1  UIKit                          0x25d6b6ad __67-[_UIViewAdditiveAnimationAction runActionForKey:object:arguments:]_block_invoke + 408
2  QuartzCore                     0x254e4959 CA::Layer::end_change(CA::Transaction*, unsigned int, objc_object*) + 96
3  QuartzCore                     0x254e54c7 CA::Layer::set_bounds(CA::Rect const&, bool) + 526
4  QuartzCore                     0x254e51e3 -[CALayer setBounds:] + 110
5  QuartzCore                     0x254e6237 -[CALayer setFrame:] + 542
6  UIKit                          0x25acc899 -[UIView(Geometry) setFrame:] + 264
7  Prevent                        0x002ea57b -[UIView(TLView) tlsw_setFrame:] (UIView+TLView.m:102)
8  UIKit                          0x25adee11 -[UIImageView _setViewGeometry:forMetric:] + 168
9  UIKit                          0x25aded63 -[UIImageView setFrame:] + 38
10 UIKit                          0x25cf0883 -[UISlider _layoutSubviewsForBoundsChange:] + 1082
11 UIKit                          0x25cf2af5 -[UISlider layoutSubviews] + 148
12 MediaPlayer                    0x23d51c6b -[MPVolumeSlider layoutSubviews] + 42
13 UIKit                          0x25acfc1b -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 546
14 QuartzCore                     0x254ee445 -[CALayer layoutSublayers] + 128
15 QuartzCore                     0x254e9c95 CA::Layer::layout_if_needed(CA::Transaction*) + 360
16 UIKit                          0x25ae2853 -[UIView(Hierarchy) layoutBelowIfNeeded] + 138
17 UIKit                          0x25ae7cc3 -[UISlider setValue:animated:] + 178
18 MediaPlayer                    0x23d52377 -[MPVolumeSlider volumeController:volumeValueDidChange:] + 78
19 MediaPlayer                    0x23db6015 -[MPVolumeController updateVolumeValue] + 252
20 MediaPlayer                    0x23d51d8b -[MPVolumeSlider didMoveToSuperview] + 126
21 UIKit                          0x25aceaa5 -[UIView(Hierarchy) _postMovedFromSuperview:] + 428
22 UIKit                          0x25ad9375 -[UIView(Internal) _addSubview:positioned:relativeTo:] + 1500
23 UIKit                          0x25ad8d8f -[UIView(Hierarchy) addSubview:] + 30
24 Prevent                        0x002e9e63 -[UIView(TLView) tlsw_addSubview:] (UIView+TLView.m:69)
25 MediaPlayer                    0x23d54b79 -[MPVolumeView _createSubviews] + 236
26 MediaPlayer                    0x23d537c5 -[MPVolumeView _initWithStyle:] + 212
27 MediaPlayer                    0x23d53859 -[MPVolumeView initWithFrame:style:] + 80
28 MediaPlayer                    0x23d53803 -[MPVolumeView initWithFrame:] + 38
29 UIKit                          0x25aefd25 -[UIView init] + 44
30 WebCore                        0x2e555733 -[WebMediaSessionHelper allocateVolumeView] + 262
31 WebCore                        0x2e5559e7 -[WebMediaSessionHelper initWithCallback:] + 394
32 WebCore                        0x2e554b17 WebCore::MediaSessionManageriOS::MediaSessionManageriOS() + 170
33 WebCore                        0x2e554a05 WebCore::MediaSessionManager::sharedManager() + 124
34 WebCore                        0x2e553c89 WebCore::MediaSession::MediaSession(WebCore::MediaSessionClient&) + 32
35 WebCore                        0x2e1e65f1 WebCore::HTMLMediaSession::create(WebCore::MediaSessionClient&) + 20
36 WebCore                        0x2e1d4fcb WebCore::HTMLMediaElement::HTMLMediaElement(WebCore::QualifiedName const&, WebCore::Document&, bool) + 1042
37 WebCore                        0x2e1fddbb WebCore::HTMLVideoElement::create(WebCore::QualifiedName const&, WebCore::Document&, bool) + 38
38 WebCore                        0x2e1c8191 WebCore::videoConstructor(WebCore::QualifiedName const&, WebCore::Document&, WebCore::HTMLFormElement*, bool) + 56
39 WebCore                        0x2e1c78e7 WebCore::HTMLElementFactory::createElement(WebCore::QualifiedName const&, WebCore::Document&, WebCore::HTMLFormElement*, bool) + 230
40 WebCore                        0x2ddd5bd1 WebCore::HTMLDocument::createElement(WTF::AtomicString const&, int&) + 88
41 WebCore                        0x2ddd5b13 WebCore::jsDocumentPrototypeFunctionCreateElement(JSC::ExecState*) + 242
42 JavaScriptCore                 0x23925c43 llint_entry + 21314
43 JavaScriptCore                 0x23925837 llint_entry + 20278
44 JavaScriptCore                 0x23925837 llint_entry + 20278
45 JavaScriptCore                 0x23925837 llint_entry + 20278
46 JavaScriptCore                 0x239206ef callToJavaScript + 334
47 JavaScriptCore                 0x238b0ca5 JSC::JITCode::execute(JSC::VM*, JSC::ProtoCallFrame*) + 36
48 JavaScriptCore                 0x236ea209 JSC::Interpreter::execute(JSC::ProgramExecutable*, JSC::ExecState*, JSC::JSObject*) + 5704
49 JavaScriptCore                 0x236e8a73 JSC::evaluate(JSC::ExecState*, JSC::SourceCode const&, JSC::JSValue, JSC::JSValue*) + 354
50 WebCore                        0x2e6865a9 WebCore::ScriptController::evaluateInWorld(WebCore::ScriptSourceCode const&, WebCore::DOMWrapperWorld&) + 196
51 WebCore                        0x2ddf0793 WebCore::ScriptController::evaluate(WebCore::ScriptSourceCode const&) + 26
52 WebCore                        0x2ddf0737 WebCore::ScriptElement::executeScript(WebCore::ScriptSourceCode const&) + 234
53 WebCore                        0x2de769dd WebCore::HTMLScriptRunner::executePendingScriptAndDispatchEvent(WebCore::PendingScript&) + 156
54 WebCore                        0x2de71f85 WebCore::HTMLScriptRunner::executeParsingBlockingScripts() + 244
55 WebCore                        0x2de6f6b1 WebCore::HTMLDocumentParser::runScriptsForPausedTreeBuilder() + 52
56 WebCore                        0x2de1802b WebCore::HTMLDocumentParser::canTakeNextToken(WebCore::HTMLDocumentParser::SynchronousMode, WebCore::PumpSession&) + 50
57 WebCore                        0x2de175bd WebCore::HTMLDocumentParser::pumpTokenizer(WebCore::HTMLDocumentParser::SynchronousMode) + 344
58 WebCore                        0x2de77de1 WebCore::HTMLDocumentParser::resumeParsingAfterScriptExecution() + 76
59 WebCore                        0x2de768c9 non-virtual thunk to WebCore::HTMLDocumentParser::notifyFinished(WebCore::CachedResource*) + 72
60 WebCore                        0x2de739c9 WebCore::CachedResource::checkNotify() + 56
61 WebCore                        0x2de737dd WebCore::SubresourceLoader::didFinishLoading(double) + 128
62 CFNetwork                      0x21eecaff ___ZN27URLConnectionClient_Classic26_delegate_didFinishLoadingEU13block_pointerFvvE_block_invoke + 78
63 CFNetwork                      0x21f89fbd ___ZN27URLConnectionClient_Classic18_withDelegateAsyncEPKcU13block_pointerFvP16_CFURLConnectionPK33CFURLConnectionClientCurrent_VMaxE_block_invoke_2 + 60
64 CFNetwork                      0x21edd8d9 RunloopBlockContext::_invoke_block(void const*, void*) + 60
65 CoreFoundation                 0x223a7411 CFArrayApplyFunction + 36
66 CFNetwork                      0x21edd793 RunloopBlockContext::perform() + 182
67 CFNetwork                      0x21edd659 MultiplexerSource::perform() + 216
68 CFNetwork                      0x21edd4f5 MultiplexerSource::_perform(void*) + 48
69 CoreFoundation                 0x2245e22f __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 14
70 CoreFoundation                 0x2245d643 __CFRunLoopDoSources0 + 222
71 CoreFoundation                 0x2245bcc1 __CFRunLoopRun + 768
72 CoreFoundation                 0x223a79a1 CFRunLoopRunSpecific + 476
73 CoreFoundation                 0x223a77b3 CFRunLoopRunInMode + 106
74 WebCore                        0x2de33511 RunWebThread(void*) + 416
75 libsystem_pthread.dylib        0x30c16deb _pthread_body + 138
76 libsystem_pthread.dylib        0x30c16d5f _pthread_start + 118

**Comment by jonathannorris** [comment]
@john-langley we will dig into this. Its odd that a WebThread thread is crashing like this, do you have any more details on the device that it happened on (iOS 7/8? a crashlytics or other report are useful)?? Also any details on the structure of the view, a screenshot would be useful. Feel free to send those details to support@taplytics.com

**Comment by jonathannorris** [comment]
2.1.84 resolves this issue.
