### ISSUE TITLE
TaplyticsVar doesn't deallocate when the parent view deallocates 

### ISSUE THREAD

**Issue by holgersindbaek** [taplytics/taplytics-ios-sdk#22]
Sometimes my view is destroyed before a block is returned for TaplyticsVar. When that happens, the app crashes, since I'm trying to set the returned taplytics variable for an attribute on my view.

How do I make the TaplyticsVar deallocate when its parent view deallocates?

**Comment by jonathannorris** [comment]
@holgersindbaek we keep a reference to the `TaplyticsVar` when its created so you can use the var multiple times and only have one instance of the variable. It sounds to me like you are keeping a strong reference to your view in the block, which should be avoided: https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/WorkingwithBlocks/WorkingwithBlocks.html

For Example: 
```
__weak UIViewController* weakVC = self;
[TaplyticsVar taplyticsVarWithName:@"test var" defaultValue:@(2) updatedBlock:^(NSObject* value) {
     if (weakVC) {
          weakVC.property = value;
     }
}];
```

**Comment by holgersindbaek** [comment]
Ok... I think I know how to do it now. Thanks.

**Comment by holgersindbaek** [comment]
@jonathannorris Just another question. I'm actually keeping a weak reference, but I'm not checking if the weak reference is still there, before setting a property on it. I'll do that from now on.

Is it possible to completely destroy the TaplyticsVar when I destroy the view I'm using it on, so the block won't be called? How would you do that? Create a reference for the TaplyticsVar and then set it to nil?

**Comment by jonathannorris** [comment]
@holgersindbaek We are planning on making an internal change to the SDK so we only hold weak references to the `TaplyticsVar`, but there are a couple edge-cases that we are still working through. We are also working on improving the documentation around TaplyticsVar's to better explain how to use them asynchronously or synchronously. I'll let you know when we have the weak linking live.

**Comment by holgersindbaek** [comment]
Ok... that didn't really answer my question though. How can I destroy a TaplyticsVar variable? Do I just assign it to a variable and then set that variable to nil?

**Comment by jonathannorris** [comment]
Currently we keep a strong reference to the variable, so we can de-dupe and only have one instance for each variable name, but that also means when you nil your reference to the variable it wont be immediately destroyed. So you are going to need the check for nil weak reference for now.

**Comment by holgersindbaek** [comment]
@jonathannorris Did you fix this?!
