### ISSUE TITLE
Infinite loop +[TLTableViewDataSource tlsw_tableView:cellForRowAtIndexPath:] in version 2.7.18

### ISSUE THREAD

**Issue by nipapadak** [taplytics/taplytics-ios-sdk#23]
I was wondering if this issue was fixed in 2.8.0, thanks.

**Comment by jonathannorris** [comment]
@nipapadak We've made a bunch of changes to our internal element tracking, but I'm not sure if it will resolve your issues. Are you willing to give 2.8.0 a try? Also any specific details on how your TableView is structured is welcome (also screenshots and full stack traces are wellcome).

**Comment by nipapadak** [comment]
@jonathannorris Yes I just updated to 2.8.0 right now through pods and let you know if I see any issues in my testing. In the meantime the only logs I have is from Crashlytics [Log here](http://crashes.to/s/8f23676ad86). By the logs I cannot pin down which of my table views triggers it.

**Comment by jonathannorris** [comment]
@nipapadak we've made some underlying changes to the TableView tracking in `2.8.2` that should resolve this issue.

**Comment by nipapadak** [comment]
@jonathannorris Thanks I will update and let you know if I find any issues.

**Comment by jonathannorris** [comment]
ok going to close the issue for now.
