### ISSUE TITLE
TaplyticsVar still doesn't deallocate when the parent view deallocates 

### ISSUE THREAD

**Issue by holgersindbaek** [taplytics/taplytics-ios-sdk#24]
I'm referring to this issue, which you have closed, for reasons I don't understand:

https://github.com/taplytics/taplytics-ios-sdk/issues/22

Has this been fixed in the latest version, since you've closed the issue?!

**Comment by holgersindbaek** [comment]
??

**Comment by jonathannorris** [comment]
@holgersindbaek We've fixed this in `2.9.0`. Sorry it took so long to get out, it got wrapped up in a couple other larger changes in `2.9.0` that didn't get finished before the holidays.
