### ISSUE TITLE
How to disable "internet connection top bar"

### ISSUE THREAD

**Issue by hamdullahshah** [taplytics/taplytics-ios-sdk#26]
When the internet connection is turned off this top bar appears on the app. How to disable this ? 

![bug](https://cloud.githubusercontent.com/assets/1726321/13314448/2ec93dc2-dbe0-11e5-8ca2-6e25be77d208.png)

**Comment by cdruxerman** [comment]
Hey Hamdullah, I believe this was addressed in another support channel. I'm going to close the issue. Let me know if you need further info here.

**Comment by opiator** [comment]
@cdruxerman  Can you point me to the particular support channel? We are having the same issue

**Comment by jndonald3** [comment]
@cdruxerman @hamdullahshah What was the solution to this issue? I'm also seeing the same problem
