### ISSUE TITLE
Taplytics prevent me to set my textfield first responder

### ISSUE THREAD

**Issue by hugocroch** [taplytics/taplytics-ios-sdk#34]
Hi,

I just installed Taplytics in podfile (nothing more) on my project.But since I installed it, when I try to make a textfield embedded in a UITableviewCell becoming first responder, it doesn't work. Is it an known issue and is there a solution about this? Am I crazy or is it XCode?

I installed version 2.15.3 in podfile

**EDIT**

I tried with version 2.15.8 and I have the same problem.

**Comment by cdruxerman** [comment]
Hi Hugo,

We are looking into the issue as per our discussion via email. I will keep you updated as we look investigate and resolve it.

Regards,
Cobi

**Comment by cdruxerman** [comment]
Hi Hugo, as mentioned you should be able to resolve this by using the TaplyticsDisableUITextFieldViewSW option in the StartTaplytics call.
