### ISSUE TITLE
can not set variable in swift

### ISSUE THREAD

**Issue by feemi** [taplytics/taplytics-ios-sdk#35]
let navigationBarItemHorizontalSpace: TaplyticsVar = TaplyticsVar(name: "navigationBarItemHorizontalSpace", defaultValue:0 {
            (updatedValue: NSObject?) in
            guard let value: NSNumber = updatedValue else {return}
            
            fixedSpace.width = value.doubleValue
        })

This is the generated code from your dashboard
this gives compile error in swift  cannot call  value  of non-function type nsnumber

**Comment by JeffSeto** [comment]
```swift
let navigationBarItemHorizontalSpace: TaplyticsVar = TaplyticsVar(name: "navigationBarItemHorizontalSpace", defaultValue:NSNumber(value: 0)) {
            (updatedValue: NSObject?) in
            guard let value: NSNumber = updatedValue as? NSNumber else {return}
            
            fixedSpace.width = value.doubleValue
        }
```
The dashboard currently generates older Swift syntax.  This code should work for Swift 3.
