### ISSUE TITLE
PushNotifications are not receiving in iOS

### ISSUE THREAD

**Issue by ajay2c9** [taplytics/taplytics-ios-sdk#52]
I updated the latest pod. Push notifications are not receiving in iOS 11 Versions.and working fine in iOS10 Versions.Please give suggestions. to resolve this issue

**Comment by cdruxerman** [comment]
Hi @ajay2c9 could you share which iOS 11 version you're using?

**Comment by cdruxerman** [comment]
Hi @ajay2c9 I just wanted to follow up on this here as well. Have you had an opportunity to test on the newest version of iOS 11?

**Comment by ajay2c9** [comment]
Its working fine in iOS 11. 
Thank you for support
