### ISSUE TITLE
Taplytics startup triggering Exception Breakpoint in Xcode

### ISSUE THREAD

**Issue by kunal30xi** [taplytics/taplytics-ios-sdk#67]
Xcode 10.1 (10B61)
MacOS Mojave 10.14.2
Taplytics version: 2.37.0
iOS Simulator version: iPhone 7 (11.4)
When executing the start method with the appropriate API Key
```
+ (void)startTaplyticsAPIKey:(nonnull NSString*)apiKey;
```

in the following method of the AppDelegate 
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
```

an exception breakpoint is being triggered right at the `window makeKeyAndVisible` line. 

The following line is logged to the Console as well:

`2019-01-15 17:12:39.885121-0500 App[45694:590479] libMobileGestalt MobileGestalt.c:4130: Failed to get Computer Name, returning device name`

Removing the exception breakpoint of course allows the launch to proceed.

Any ideas on how we can get this issue resolved? We typically do development with exception breakpoints enabled so turning OFF breakpoints is not an option.

**Comment by kavitasookrah** [comment]
Hey Kunal - I wanted to confirm that we received your support ticket! Thanks for submitting it again. We'll work off that ticket to get this resolved :)

**Comment by sjavier23** [comment]
Hey @kunal30xi, I had a chance to sync with Kavita on this and it looks like your team is using a .xib launch screen. Are you able to confirm that setting `TaplyticsOptionLaunchImageType: "xib"` in your startOptions (https://docs.taplytics.com/docs/ios-getting-started#section-start-options) fixes this issue?

Let me know,
Shirley

**Comment by kunal30xi** [comment]
Hey @sjavier23 That does resolve the issue. Thank you.
