### ISSUE TITLE
Using Taplytics SDK issues a warning in App Store Connect

### ISSUE THREAD

**Issue by barakwei** [taplytics/taplytics-ios-sdk#75]
Our app uses Taplytics SDK and since yesterday we've started to receive warnings when we upload apps to the App Store:
`ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.`

It seems like your SDK still uses `UIWebView` which is deprecated. From analyzing our binary it seems like you may be a third party networking library that uses `UIWebView`.
Your SDK should use `WKWebView` instead.

**Comment by sjavier23** [comment]
Hi @barakwei just wanted to let you know that we have released version 2.45.0 of our iOS SDK which has removed the deprecated UIWebView. Please update at your earliest convenience and let us know if you have any questions. Thanks!

https://github.com/taplytics/taplytics-ios-sdk/releases/tag/2.45.0
