### ISSUE TITLE
Feature request: Carthage support

### ISSUE THREAD

**Issue by ruipfcosta** [taplytics/taplytics-ios-sdk#82]
Are there any plans to support Carthage? 
For projects where the source code is not available you only need to maintain a binary project spec, [as defined in the Carthage docs](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#binary-project-specification).

**Comment by sjavier23** [comment]
Hi @ruipfcosta thanks for reaching out! I have relayed this feedback to our Product team and we'll definitely keep you and your team posted.

**Comment by alekplay** [comment]
Please 👏 add 👏 carthage 👏 support 👏

**Comment by leslie-lau** [comment]
Hi @alekplay @ruipfcosta good news! Version 4.0.0 of the Taplytics iOS SDK includes support for .xcframeworks as well as support for Carthage. We’ve included steps in our docs to get started.

Link: https://github.com/taplytics/taplytics-ios-sdk/releases/tag/4.0.0
